title: COVID-19 Vacuna.uy
author:
  name: David Giordano
  email: 3dgiordano@gmail.com
description: Monitor de vacunación COVID-19 de Uruguay por @3dgiordano
remote_theme: jekyll/minima

minima:
  social_links:
    twitter: 3dgiordano
    github: 3dgiordano
    linkedin: davidgiordano
