title: COVID-19 Vax Uruguay
author:
  name: David Giordano
  email: 3dgiordano@gmail.com
description: Uruguay COVID-19 Vaccination Monitor by @3dgiordano
remote_theme: jekyll/minima

lang: en 
languages: ["en", "es"]

minima:
  social_links:
    twitter: 3dgiordano
    github: 3dgiordano
    linkedin: davidgiordano
